### ISSUE TITLE
Geschwindigkeitsproblem mit Schwadmäher

### ISSUE THREAD

**Issue by IROKILLER** [Stephan-S/FS25_AutoDrive#10]
Wenn ich den Schwadmäher der in Straßenstellung mit Schneidwerkswagen hinten dran Fahren lasse fährt er nur 12 KM/H. Wenn ich ihn in Arbeitsstellung bringe fährt er 45 KM/H auf der Straße. Ich denke das Autodrive der Meinung ist wenn er in Straßenstellung ist das er Rückwährts fährt und deswegen nur 12 KM/H fährt.

Video
https://youtu.be/no_xaSYNDdI

**Comment by ThomasMatern** [comment]
@IROKILLER das ist ein Bug im Spiel, nicht in AutoDrive. Das gleiche passiert, wenn du den eingebauten AI driver benutzt. AutoDrive versucht 45km/h zu fahren, aber Giants erlaubt nur 12km/h. Falls Giants das behebt, wird das (hoffentlich) automatisch in AD funktionieren.
