### ISSUE TITLE
Hilfsfenster links ist weg 

### ISSUE THREAD

**Issue by Ma1980B** [Stephan-S/FS25_AutoDrive#11]
Bei mir lässt sich nach autodrive installation das hilfefenster nicht mehr anzeigen

**Comment by Iwan1803** [comment]
Hilfefenster? Meinst du das F1-Menü?

**Comment by Ma1980B** [comment]
ja genau das

**Comment by Iwan1803** [comment]
F1 drücken und dann sollte es wieder erscheinen oder hast du das AD-HUD dort platziert, wo eigentlich das Menü ist?

**Comment by Ma1980B** [comment]
nein habe noch keine belegung geändert aber es erscheint nicht mehr wenn ich f1 drücke

**Comment by Iwan1803** [comment]
Ist das Hilfemenü vorhanden, wenn du ein neues savegame ohne jegliche Mods erstellst?
Die Log-Datei könnte ansonsten hilfreich sein.

**Comment by Iwan1803** [comment]
Falls CoursePlay im Einsatz ist, dann bitte aktualisieren:
https://github.com/Courseplay/Courseplay_FS25/releases

**Comment by Ma1980B** [comment]
ja das menü ist ohne mods da wenn ich dann nur autodrive reinmache ist es weg

**Comment by Iwan1803** [comment]
Logdatei?

**Comment by Ma1980B** [comment]
konnte ich jetzt so nix erkennen kann ihn aber mal hochladen

**Comment by Iwan1803** [comment]
Sehr schön 😀
