### ISSUE TITLE
Kurven mit dem Mausrad funktioniert nicht

### ISSUE THREAD

**Issue by Ralle1970** [Stephan-S/FS25_AutoDrive#12]
Hi,
 Erstmal einen SUPER GROßEN DANK, dass ihr so schnell das AD wieder ins Spiel gebracht habt.
SUPER LEISTUNG.

Sicher gibt es vielleicht noch hier und da kleine Fehlerchen ;)

Ich wollte gerade Strecken bauen und habe festgestellt, dass man die Kurven nicht mit dem Mausrad erstellen kann.
Muss diese leider mit Punkten setzen. Vielleicht kann man das ja mal bei Gelegenheit fixen, wäre super.

Danke und Grüße

**Comment by nils1981-spass** [comment]
Habe das gleiche Problem bei mir festgestellt.

**Comment by regs1980** [comment]
Wie ist denn eure Herangehensweise für eine Kurve mit Mausrad?
Bei mir funktioniert es sogar mit gedrückter Strg und Alt Taste eine 2 Wege kurve.

**Comment by Ralle1970** [comment]
Es ist die gleiche wie bei LS22.

**Comment by regs1980** [comment]
> Es ist die gleiche wie bei LS22.

Dann muss es funktionieren, macht es doch hier auch.
https://drive.google.com/file/d/1W75Ne_kcOkh6TEDY1DE510f6gnnEqgsJ/view?usp=sharing

**Comment by Kitekater** [comment]
Funktioniert ohne Probleme. Du musst nur 2 verbundene Punkte vor der Kurve haben, sonst wirds nix, da er nicht weiss, wie er die Kurve "einschlagen" soll

**Comment by Ralle1970** [comment]
Also ich habe es jetzt nochmal versucht.

Ich weiß nicht, woran es gelegen hat. Jetzt funktioniert es.
Danke an [regs1980] für das Video und [Kitekater] nochmal für den Hinweis.

Was ich aber festgestellt habe, die Kurven zeichnet er nur dann, wenn man das Mausrad zu Beginn nach »unten« dreht.

Nochmals Danke für die Hilfe.
