### ISSUE TITLE
Update/Create da translation

### ISSUE THREAD

**Issue by Michaelbjerg21978** [Stephan-S/FS25_AutoDrive#14]
I have finnaly checked my translation from 22, now updated too 25.
Sorry too iwan for the wrong signs in my 22 file.

Hope you will use this:
[translation_da.zip](https://github.com/user-attachments/files/18253922/translation_da.zip)

Best regards:
Mihael

**Comment by ThomasMatern** [comment]
https://github.com/Stephan-S/FS25_AutoDrive/pull/7
