### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by coolfarmer** [Stephan-S/FS25_AutoDrive#22]
Is this mod fully compatible with multiplayer?
Are courses shared between players?
Are there any known issues related to multiplayer?

A FAQ about multiplayer in the README.md would be helpful.

Thanks!

**Comment by proactivepcc** [comment]
I'm running it multiplayer, works well.  Courses are shared.

**Comment by Iwan1803** [comment]
You can use AD in SP, hosted MP and on server.
There are only 2 things, that doesn't work on a server: the route manager and the automatic creation of a route network, if there is none in the savegame.
I will add this in the wiki as the Readme.md isn't the right place for it.
