### ISSUE TITLE
Parken und Parkplatz zuweisen

### ISSUE THREAD

**Issue by ijanda** [Stephan-S/FS25_AutoDrive#25]
Klappt leider nicht. Parkplatzzuweisung ist funktionslos. Das Parken selbst extrem ungenau. Man muss mind 1 Fahrzeugbreite Platz lassen damit rückwärts einparken überhaupt klappt. Die Fahrzeuge sind sehr weit von der Führungslinie entfernt. (Einstellungen alle auf Minimum). 
Ansonsten sehr gute Arbeit. Klappt generell schon ziemlich gut.

**Comment by Iwan1803** [comment]
"klappt nicht" ist genau so eine hilfreiche Aussage wie "geht nicht".
Zur Erinnerung: Parkplatz zuweisen geht nur im Editor-Modus und gilt dann für das ausgewählte Gerät/Fahrzeug.

**Comment by ThomasMatern** [comment]
Closing in favour of #42
