### ISSUE TITLE
Kurven zeichnen funktioniert nicht

### ISSUE THREAD

**Issue by nils1981-spass** [Stephan-S/FS25_AutoDrive#27]
Wenn ich mit dem Mausrad eine Kurve zeichnen möchte funktioniert nicht egal was ich versuche die Liebe bleibt immer grade. Habe schon versucht :

2 Punkte vor dem Kurven Beginn den Punkt zu nehmen 

Bestehende Kurven neu anzulegen 

Tastenkombinationen STRG+ALT und linke Maustaste

Mausrad nach oben oder unten bewegt

Autodrive neu installiert

bei allen diesen Anwendungen bleibt die Linie grade bzw. wird direkt diagonal gezogen.

was kann ich noch machen

**Comment by Iwan1803** [comment]
Seltsamkeiten, denn ich habe damit keine Probleme. Ein Screenshot und deine Log könnten hilfreich sein.

**Comment by nils1981-spass** [comment]
![IMG_8263](https://github.com/user-attachments/assets/c27644b9-3d13-43b8-af68-fc648d49e9d8)
![IMG_8265](https://github.com/user-attachments/assets/a1c14774-8762-4215-b5e1-e7411d0555e9)

egal an welchen Kurven immer das gleiche die Linie lässt sich nicht ziehen mit dem Mausrad 

Habe auch eine neue Karte geladen trotzdem das gleiche, habe es noch mal auf dem LS22 probiert dort hat es sofort geklappt.

**Comment by Iwan1803** [comment]
Bitte mal Courseplay aktualisieren, falls noch nicht geschehen:
https://github.com/Courseplay/Courseplay_FS25/releases

**Comment by nils1981-spass** [comment]
https://1drv.ms/t/c/473e0d36d7905905/ERc8ZzFpGjdFsKkBLO4kM5MBVlE8DtDr6mneHjd1e1PawA

**Comment by nils1981-spass** [comment]
Habe mal meine log Daten geschickt mit dem Coursplay Update ist das Problem noch nicht gelöst bei mir

**Comment by Rhoendiesel** [comment]
Ich habe das gleiche Problem egal auf welcher Karte. Du kannst das Mausrad drehen und nichts passiert.

**Comment by Iwan1803** [comment]
Was hat ein LS22-Mod im mods-Ordner von LS25 zu suchen: FS22_JohnDeere_Gewicht900kg?
fehlerhafte Mods: FS25_asw271, FS25_asw271_edit__1_, FS25_baseTree_prefab, FS25_GraphicModV1_Fps_Boost, FS25_gx520, FS25_LoneHills_UNZIP_2, FS25_LosCorrales_2K25_UNZIP, FS25_ManureHeap_Nosnap__1_, FS25_radium255, KETCHUP_UNZIP, maize, PIZZA_UNZIP, _EXTRACT__Ground_Deformation_2X__1_, _EXTRACT__Ground_Deformation_5X__1_
Dazu noch die Datei fürs Internet-Radio fehlerhaft und wo ist das Laden des savegames?

Verschieb am besten alles (bis auf AutoDrive) mal aus dem mods-Ordner in einen anderen Ordner und versuch das ganze dann mit einem neuen savegame noch mal.
Klappt es dann, verschiebst du 2-3 Mods wieder zurück und probierst es erneut. 
Wenn der Fehler wieder auftritt, liegt es wohl an einem Mod, welcher dazwischenfunkt.

**Comment by nils1981-spass** [comment]
Es funktioniert nun war lag wohl an den Mods

noch mal Danke

**Comment by Iwan1803** [comment]
Wäre nur die Frage: welche waren denn nun Schuld?

**Comment by nils1981-spass** [comment]
Die Fehlerhafte Mod war die FS25_QuickCamera
Von meinem iPhone gesendet

Am 27.12.2024 um 14:31 schrieb Iwan1803 ***@***.***>:

﻿

Closed #27<https://github.com/Stephan-S/FS25_AutoDrive/issues/27> as completed.
