### ISSUE TITLE
AD und Strassenverkehrs regeln

### ISSUE THREAD

**Issue by Mirohdir** [Stephan-S/FS25_AutoDrive#29]
hallo, wie auf YT schon erwähnt und gefragt habe ob es möglich ist AD noch mit den Strassen verkehrsregeln zu verknüpfen stelle ich die Frage hier erneut xD.
Also:
ist es möglich und wäre das was für das AD taem zu versuchen AD mit so aufzubauen das auf Ampeln Stopschilder etc regaiert werden kann btw. das AD darauf reagiert. wenn ja wäre das Mega

**Comment by Iwan1803** [comment]
In LS22 gab es die Ampeln von Achimobil, welche eine Kollibox hatten. War die Ampel grün, fuhr AD durch und war sie rot, blieb AD da stehen.
Da die Vanilla-Ampeln sowas nicht haben, wird eine Umsetzung kaum möglich sein. Gleiches gilt für Stop-Schilder.

**Comment by Mirohdir** [comment]
> In LS22 gab es die Ampeln von Achimobil, welche Kollibox hatte. War die Ampel fuhr grün, AD durch und War-Säuge, hüten Sie sich auf. Da die Vanilla-Ampeln war nicht nicht, wird ein Umsetzungs-Limbares-Kind. Gleiches vergoldet für Stop-Schilder.

na toll und dafür hab ich mir nen github Acc erstellt ? das hättest du mir auch auf YT beantworten können -.-

**Comment by Mirohdir** [comment]
In LS22 gab es die Ampeln von Achimobil, welche Kollibox hatte. War die Ampel fuhr grün, AD durch und War-Säuge, hüten Sie sich auf. Da die Vanilla-Ampeln war nicht nicht, wird ein Umsetzungs-Limbares-Kind. Gleiches vergoldet für Stop-Schilder.

na klasse dafür hab ich mir jetzt nen github account angelegt ? das hättest du mir auch auf YT beantworten können

**Comment by Mirohdir** [comment]
> In LS22 gab es die Ampeln von Achimobil, welche Kollibox hatte. War die Ampel fuhr grün, AD durch und War-Säuge, hüten Sie sich auf. Da die Vanilla-Ampeln war nicht nicht, wird ein Umsetzungs-Limbares-Kind. Gleiches vergoldet für Stop-Schilder.

na klasse dafür hab ich mir jetzt nen github account angelegt ? das hättest du mir auch auf YT beantworten können

**Comment by Iwan1803** [comment]
Ich habe nicht gesagt, das wir uns das nicht anschauen können aber im Moment sehe ich da keine Chance auf eine Umsetzung.
