### ISSUE TITLE
translation correction Spanish and Spanish America

### ISSUE THREAD

**Issue by santixV8** [Stephan-S/FS25_AutoDrive#3]
Hello, I would like to share a correction of the translation into Spanish, Also to add the translation for Spanish America, but I don't know how to use github. I hope to have an answer and be able to collaborate with you. Greetings from Uruguay

**Comment by santixV8** [comment]
[AD_spanish_translation.zip](https://github.com/user-attachments/files/18247376/AD_spanish_translation.zip)

**Comment by KCHARRO** [comment]
Hello again, I am also one in charge of Spanish translation...

**Comment by santixV8** [comment]
Hi bro, tell me if I did the pull request right. thanks

**Comment by KCHARRO** [comment]
You do not need to attach the ".zip"....

Just edit the xml and make the pull request...

to add "spanish_ea.xml" make a branch, add the file and make the pull request...

**Comment by ThomasMatern** [comment]
https://github.com/Stephan-S/FS25_AutoDrive/pull/20
https://github.com/Stephan-S/FS25_AutoDrive/pull/21
