### ISSUE TITLE
Autodrive on map

### ISSUE THREAD

**Issue by prawler74** [Stephan-S/FS25_AutoDrive#31]
Hi

Fantastic work....again. So much so that i donated some cash....Keep it up.

One question. Am i missing something, or is the function to turn on the autodrive cenerated courses on the map/minimap missing?
Really liked to be able to turn that on.....

Best regards
Bjørn

**Comment by prawler74** [comment]
Strange. 
I cant see them...

**Comment by Mwirenfeldt** [comment]
Also make sure that you are in edit-mode. Lines need to be visible ingame. :-)
