### ISSUE TITLE
Drescher abtanken 

### ISSUE THREAD

**Issue by Ganelcer** [Stephan-S/FS25_AutoDrive#36]
Hallo,

leider habe ich das Problem, das der Abfahrer nicht den Drescher abtankt.
Ich spiele mit CP und AD. 
Der Drescher hat eine CP Kurs und fährt diesen auch ab, im AD ist der Abfahrer auf Fahren eingestellt und Ladeziel: Feld 6.
Der Abfahrer ist nur im AD aktiv, dort habe ich den Modus "Drescher abfahren" eingestellt. Ladeziel: Feld 6 und Entladeziel: Silo
![LS25-01](https://github.com/user-attachments/assets/2e5054ad-1fe1-461e-8f6f-f9210f629e48)
![LS25-02](https://github.com/user-attachments/assets/0f69d376-3913-4d18-8c1f-15f52f4b19b4)
Gaints Ablader ist deaktiviert.

Welche Informationen muß ich noch beisteuern um das Problem zu beheben oder habe ich einfach eine Option übersehen.

MFG

**Comment by gnuffel1** [comment]
Hi

beim Abfahrer im AD muss noch das CP zu gewiesen werden.  Rechtsklick auf das Lenkrad

**Comment by SnyderAnrw** [comment]
nein. der abfahrer braucht kein CP.

aber es könnte vielleicht am schwad liegen. irgendwo hab ich was in den einstellungen geseehn von "schwad erkennen" oder so. aber keine beachtung geschenkt. man sieht ja das er den drescher gefunde hat aber irgend etwas im weg ist.

**Comment by ThomasMatern** [comment]
@Ganelcer kannst du bitte Screenshots mit dem AD HUD machen?
Wenn du AD zum abladen benutzt, muessen der Drescher und der Abfahrer das gleiche AD Ziel ausgewaehlt haben. Das AD HUD vom Drescher zeigt dir eine Warnung an falls das falsch konfiguriert ist:
![image](https://github.com/user-attachments/assets/089cf382-51fd-43b3-8b02-aa4ff1793231)

**Comment by Ganelcer** [comment]
@ThomasMatern bitte bei den Screenshots oben in der Mitte nachschauen, dort habe ich das Autodrive-Hud.

Habe in der Zwischenzeit ein Spielstand nur mit AD und CP gestartet, auch hier lädt AD den Drescher nicht ab. 
Habe die Einstellungen aus LS 22 mit denen in LS 25 abgeglichen, an denen ist nichts auffallendes.

Was ich aber gemerkt habe, das sich mein Rechner seit gestern im LS 25 aufhängt bzw. die Map abstürzt. 

MFG

**Comment by ThomasMatern** [comment]
@Ganelcer kannst du bitte mal CoursePlay aktualisieren? 8.0.0.1 hat einige wichtige Aenderungen fuer die Zusammenarbeit mit AD, aber direkt zu 8.0.0.2 zu gehen kann auch nicht schaden.
Falls das nicht hilft, kannst du bitte mal dein savegame upload ueberpruefen? Der link funktioniert nicht.

**Comment by Ganelcer** [comment]
@ThomasMatern vielen Dank für den Hinweis, habe CP aktualisiert.

Würde mich gleich melden was funktioniert.
