### ISSUE TITLE
There is no Ukrainian translation

### ISSUE THREAD

**Issue by Goldenfenix3000** [Stephan-S/FS25_AutoDrive#4]
The mod does not have a Ukrainian translation, although the game supports this language. Here is the translation file, in the archive. Add the file translation_uk.xml to the archive with the mod along this path- FS25_AutoDrive.zip\translations
[translation_uk.zip](https://github.com/user-attachments/files/18247071/translation_uk.zip)

**Comment by ThomasMatern** [comment]
@Goldenfenix3000 there is an existing pull request (not from you): https://github.com/Stephan-S/FS25_AutoDrive/pull/18
Please check if this solves your request.

**Comment by ThomasMatern** [comment]
https://github.com/Stephan-S/FS25_AutoDrive/pull/18
