### ISSUE TITLE
CP activates AD, but AD does not activate CP.

### ISSUE THREAD

**Issue by erksartori** [Stephan-S/FS25_AutoDrive#41]
Version
8.0.0.2

Game Version
1.4.0.0

SP/MP
SP (Singleplayer)

What happened?
CP activates AD, but AD does not activate CP.

How can we reproduce this?
I'm harvesting straw, when it's full it leaves the CP and goes to the AD, to make the journey to unload the straw, when it returns it gives a message and doesn't harvest the straw again.

Message: "Driver of 3650: Not able to start AI Helper"

What did you expect to happen?
Depending on the FS22 version, or earlier, as soon as the tractor returns from transport it starts harvesting from where it left off.

Attach your log.txt!
[log.txt](https://github.com/user-attachments/files/18264726/log.txt)

Screenshots
![2300320_2](https://github.com/user-attachments/assets/703c1a90-7136-4c77-9061-6185fcfd1135)

**Comment by erksartori** [comment]
Also open in CP as CP #166

**Comment by ThomasMatern** [comment]
@erksartori right-click on the AI helper icon in the AD hud to switch to CP mode - the icon changes from the AI helper icon to the CP icon.
![image](https://github.com/user-attachments/assets/37095406-3352-4395-8ddb-7bc8c6b83f2b)

**Comment by Resandise** [comment]
@ThomasMatern 

On his screenshot, the CP Wheel is green, so that is not the issue.

![399032436-703c1a90-7136-4c77-9061-6185fcfd1135](https://github.com/user-attachments/assets/7e1da293-7400-433f-8de3-f4488fa3dcc5)

**Comment by ThomasMatern** [comment]
@Resandise you missed my point: this is NOT the CP icon, this is the icon for the Giants AI helper. Right-click on this icon to switch to CP - as per my screenshot.

**Comment by Resandise** [comment]
I missed the memo that there was an option to chose between giants helper and CP, my bad, sorry.

**Comment by Resandise** [comment]
@ThomasMatern question though, when I hover my mouse, it say AI/CP/AIVE.  What is AIVE?

**Comment by ThomasMatern** [comment]
AI Vehicle Extension - https://github.com/Mogli12/AIVehicleExtension
No idea if this will be available for FS25 again.

**Comment by erksartori** [comment]
Thanks for the explanation, I hadn't found anything that explains this function. Thanks and congratulations on the work.
