### ISSUE TITLE
Probleme mit Universal Autoload (ual) bei Verwendung Autodrive (ad)

### ISSUE THREAD

**Issue by StahlGERwitter** [Stephan-S/FS25_AutoDrive#46]
Hallo liebes Autodrive-Team,
Ich habe ein Problem das mein ual bei der Nutzung von Autodrive den Ladevorgang nicht mehr ausführt.
Das Problem begann erst, als ich den Autodrive geladen habe und ich konnte die Ursache auch auf diesen Mod zurückführen, da es ohne Autodrive normal funktioniert. Festgestellt habe ich es auf der Riverbend Springs Map.
Anbei ist die log-Datei, Screenshot ohne ad / mit ad, Screenshot mit den Versionsnummern von ual/ad.
Auf dem Screenshot mit Autodrive sieht man, das unter dem F1-Hilfemenü der Tastenbefehl zum Beladen fehlt. Auch durch drücken der dafür zugewiesenen Tasten, startet der Ladevorgang nicht. Die Neuzuweisung des Tastenbefehls zur Beladung bleibt ebenfalls ohne Erfolg.

[log.txt](https://github.com/user-attachments/files/18267461/log.txt)
![mit ad](https://github.com/user-attachments/assets/8407f8d7-cf57-4db1-af90-948ccd5470b6)
![ohne ad](https://github.com/user-attachments/assets/2eb59964-fc77-479a-aefe-9b208a44c26a)
![version ad](https://github.com/user-attachments/assets/a597f50d-cb9d-4095-b6d3-6b2384a0f15a)
![version ual](https://github.com/user-attachments/assets/749fd890-52ab-4899-8ac6-71de79e8cb98)

**Comment by ThomasMatern** [comment]
Deine Logdatei enthaelt viele Fehler die nichts mit AD zu tun haben. Bitte deaktiviert ALLE mods ausser UAL und AD.
Das F1 Menue zeigt nicht immer alle Optionen an und aus unbekannten Gruenden scheint Giants die Tastenkombinationen fuer AD zu bevorzugen. Wenn du die Karte ausblendest (Taste 9 mehrfach druecken), solltest du mehr Optionen sehen.

AD und UAL arbeiten problemlos zusammen.
![image](https://github.com/user-attachments/assets/c002f184-6a98-4ab9-876e-a7bbc37ec1ac)

**Comment by StahlGERwitter** [comment]
konnte das Problem soeben selbst lösen, indem ich die Steuerung auf Standard zurückgesetzt habe. obwohl ich dort noch nie etwas geändert hatte, hat es mein Problem gelöst.
