### ISSUE TITLE
AutoDrive don't start Courseplay

### ISSUE THREAD

**Issue by StSt1408** [Stephan-S/FS25_AutoDrive#5]
I have generated a Courseplay Course. Then I start AutoDrive to drive to the Field. When AutoDrive arrives the Field it says "Could not start AI Worker". But he should start Courseplay.

Additional information
Hutan Pantai
FS25 Server over Steam on Windows 11.
FS25 Client over Steam on Windows 11.

Do you need Logfiles?

Thank you for give us AutoDrive to FS25.
Best regards
Stefan

**Comment by Iwan1803** [comment]
The message "Could not start AI Worker" states, that you didn't switch the button from AI to CP by right clicking on it 😉

**Comment by StSt1408** [comment]
Thank you vor Information

**Comment by StSt1408** [comment]
Thank you for information

**Comment by kaffeebart** [comment]
Kann man den Standard auf CP einstellen? 
is it possible to set CP as standard?

**Comment by Iwan1803** [comment]
Nein, denn dann würden wir ja voraussetzen, das jeder auch CoursePlay benutzt.
Da man es ja nur einmal umstellen muss, sehe ich da auch kein Problem drin.
