### ISSUE TITLE
AutoDrive Kreuzungen

### ISSUE THREAD

**Issue by StSt1408** [Stephan-S/FS25_AutoDrive#51]
Hallo, bei Mario Hirschfeld auf YouTube wurde eine Funktion präsentiert wo man Kreuzungen platzieren kann mit denen die Vorfahrtsregelung (so hab ich das im Video verstanden) kommt.

Wird diese Funktion noch verbessert und Fehler behoben oder wurde diese verworfen?

L.G. Stefan

**Comment by matze0301** [comment]
So wie ich es verstanden habe, wird das ein separater Mod, der noch im Giants-Modhub auf seine Veroeffentlichung wartet.

**Comment by Iwan1803** [comment]
Es ist ein Mod, welchen Willi erstellt hat. Letzter Stand war, das er ihn in den Modhub bringen möchte.
Somit heißt es einfach Gelduld haben und warten 😉

**Comment by StSt1408** [comment]
Danke für die Informationen
