### ISSUE TITLE
Hilfestellung

### ISSUE THREAD

**Issue by noahguyer** [Stephan-S/FS25_AutoDrive#54]
Hey Ich habe Auodrive heruntergeladen und bin aktuell auf der Map Zielonka unterwegs und es hat keine Eingefahrenen Punkte muss ich die selber alle einfahren ? Wenn nicht wo kann ich sie herunterladen und wo muss ich sie einfügen?

**Comment by ThomasMatern** [comment]
@noahguyer hier werden nur Bugs und Features diskutiert. Fuer generelle Hilfe haben wir einen Discord server. https://discord.gg/2XfnM59DFy
