### ISSUE TITLE
Sämaschine mit Saatgut und Dünger füllen

### ISSUE THREAD

**Issue by franky-bb** [Stephan-S/FS25_AutoDrive#61]
Im LS22 war es mit AD möglich die Sämaschinen mit Saatgut und Dünger mit einem Kurs automatisch befüllen zu lassen. Im LS25 fordert das Spiel, dass man zuerst die Sämaschine aufklappt. Erst danach ist ein befüllen möglich. Bei Sämaschinen über 6 Meter sehr schwierig. Ich wollte dafür ein solches Silo verwenden.

https://www.farming-simulator.com/mod.php?mod_id=303302&title=fs2025

Kann man das im AD so umbauen, dass alle Sämaschinen im eingeklappten Zustand das befüllen zulassen.
Danke an das AD Team. Ihr seid großartig.

**Comment by regs1980** [comment]
Wenn du von der Bednar OMEGA OO 6000 FL Sämaschine redest, was die einzige ist im FS25, die man zum Befüllen erst in den Arbeitsmodus bringen muss. 
Da kannst du bei Giants nachfragen, ob sie das ändern können. 
Die LEMKEN Solitair 12 kann das befüllen im Straßenmodus auch, obwohl der Deckel nicht aufgeht, dieser geht erst im Arbeitsmodus auf.
