### ISSUE TITLE
Autodrive navigation is so slow

### ISSUE THREAD

**Issue by allcoast** [Stephan-S/FS25_AutoDrive#63]
It is so slow navigating. seems like it doesnt know how to make up its mind...  and the network, as you can see is not major. 

![2024-12-30_16h25_20](https://github.com/user-attachments/assets/3356b591-e6ed-40c5-8793-3079381ea9c0)

**Comment by allcoast** [comment]
I have tried mapping every way till sunday and still, decision making is trash, it goes around the map, when there are clearer paths.

**Comment by Roby1164** [comment]
This is nothing new. Crossroads should be done with curves and not straight lines, otherwise it is normal for the vehicle to slow down a lot. This has always worked this way. Here is an example:
![Screenshot_16](https://github.com/user-attachments/assets/33589838-18f6-43f3-8102-c06386df77be)

**Comment by Iwan1803** [comment]
AD calculates the driving speed based on the angles of the waypoints to each other.
Less waypoints in a curve = higher angles = lower speed.
