### ISSUE TITLE
Bug? When StonePicking Continues to loop after job complete

### ISSUE THREAD

**Issue by RogerL75** [Stephan-S/FS25_AutoDrive#64]
Hi,

When using the stone picker to collect stones off a field and having set it to unload the stones at a point, it will restart from the starting point after it is finished (Using CoursePlay).  The stone picker also seems not to hand over to AD once it is full when using the native AI helper.

**Comment by Iwan1803** [comment]
If CoursePlay doesn't start a the the right point, this is not a problem of AD. We only handover to CP if the CP button in the AD HUD is active.
The AI helper doesn't know about AD and so there is no co-work.
