### ISSUE TITLE
CP als Standard-Übergabe-Button im HUD

### ISSUE THREAD

**Issue by Kitekater** [Stephan-S/FS25_AutoDrive#66]
Hallo zusammen,

der Übergabebutton an den Helfer ist standardmäßig der integrierte AI.
Rechtsklick ändert ihn ja auf CP.

Gibt es die Möglichkeit ihn generell auf CP umzustellen, bzw. kann man es einbauen, das er sich die letzte Einstellung merkt?

Spiele auf MP.

Gruß Marc

**Comment by andremeyer123** [comment]
Autodrive übergabe an Courseplay #24   Fixed (in next release)
