### ISSUE TITLE
Doesn't (un-)load

### ISSUE THREAD

**Issue by zaubereR167** [Stephan-S/FS25_AutoDrive#9]
I’m really excited that Autodrive is available for FS25; however, I’m already encountering problems right from the start. The AI-generated road network uses blue lines, meaning it’s drivable in both directions, even though the road is wide enough and two lanes are generated side by side. Now I have to manually change all two-lane roads into single-lane ones.

Additionally, the unloader can’t unload the combine harvester because the unloading area is blocked, even though nothing is in the way and crop avoidance is deactivated.

The third issue is that AD doesn’t correctly recognize the unloading triggers and won’t unload into a multi-fruit silo. I have to disable AD and manually press unload each time. Even a route passing over the trigger of the in-game silo NL16-22 6000 causes the driver to simply stop, even though that wasn’t the destination, regardless of whether collision detection is on or off.

**Comment by Iwan1803** [comment]
3 "reports" in one issue? 🙄
1st: yes, to have change the lanes by yourself. AD uses the splines from the map to auto create a network.
2nd: screenshots of the situation would be nice.
3rd: same like 2nd.

**Comment by MrZeD9999** [comment]
im having the same issue
its with the pea harvester also i cant get the offset pipe right do i need to change it on the harvester or each tractor
![Tractor help](https://github.com/user-attachments/assets/3535bda9-82ae-4311-b5b9-b91258051000)
![Harvester help](https://github.com/user-attachments/assets/ba382d8a-fb00-46fa-919d-c2e62cab6788)

**Comment by MrZeD9999** [comment]
the small quick fix i have done is to use the load and unload mode and set that up with a courseplay start then use the courseplay unload combine and have the offset on that one.
![tractor fix](https://github.com/user-attachments/assets/3f2ea259-10fd-43af-8b7d-793618a7372e)

**Comment by MrZeD9999** [comment]
ok after more testing it will do it if i open the pipe out but some reason the ai isnt doing that. and when it goes to unload the ai parks on the crops. but if i take control and manually put the pipe out it starts to unload.
![2300320_78](https://github.com/user-attachments/assets/769fdd44-5847-44e5-ac0d-e9d1e55bad8a)

**Comment by Iwan1803** [comment]
The problem is the very short pipe/belt.

**Comment by ThomasMatern** [comment]
@MrZeD9999 please update CoursePlay. Version 8.0.0.0 does not work well with AD.

**Comment by zaubereR167** [comment]
update worked for me , thx

**Comment by Iwan1803** [comment]
[Courseplay for FS25 v8.0.0.3](https://github.com/Courseplay/Courseplay_FS25/releases/tag/8.0.0.3)
